import = [
  "~/.config/alacritty/themes/github_dark_default.toml",
  # "~/.config/alacritty/transparency.toml",
]

[font]
size = 14

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[font.offset]
y = 2

[mouse]
hide_when_typing = true

[shell]
program = "/bin/zsh"

[window]
decorations = "none"

[window.padding]
x = 30
y = 30
