import = [ "~/.config/alacritty/rose-pine.toml" ]

[font]
size = 16

[font.bold]
style = "Bold"

[font.italic]
style = "Medium Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Medium"

[font.offset]
x = -1
y = 4

[mouse]
hide_when_typing = true

[shell]
program = "/bin/zsh"

[window]
decorations = "none"

[window.padding]
x = 30
y = 30
