# github Alacritty Colors

# Default colors
[colors.primary]
background = '#0d1117'
foreground = '#ffffff'

# Normal colors
[colors.normal]
black   = '#0d1117'
red     = '#ff7b72'
green   = '#3fb950'
yellow  = '#d29922'
blue    = '#58a6ff'
magenta = '#bc8cff'
cyan    = '#76e3ea'
white   = '#b1bac4'

# Bright colors
[colors.bright]
black   = '#6e7681'
red     = '#ffa198'
green   = '#56d364'
yellow  = '#e3b341'
blue    = '#79c0ff'
magenta = '#d2a8ff'
cyan    = '#b3f0ff'
white   = '#b1bac4'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ffa198'

